# -*- coding: utf-8 -*-
"""Build the teaching hub — the index pages that make the decks browsable.

    python3 build_teaching.py
    python3 build_teaching.py --check     # exit 1 if anything is out of date

Writes an index.html for the hub, for each affiliation, and for each course
that has a directory of decks:

    teaching/index.html
    teaching/<affiliation>/index.html
    teaching/<affiliation>/<course>/index.html

Framing (which affiliations, which courses, how they read) comes from
teaching_data.py. Weeks are not listed anywhere: this script walks the course
directory, finds week<N>/lecture/ and week<N>/live/, and takes each deck's
name from its own <title>. Add a week folder and it appears here; there is no
second place to update.

Only lecture and live-session decks are indexed. Games, quizzes, brackets and
shortlist rounds are reachable from inside a live deck during a session and
are deliberately not listed.

Never hand-edit the generated index.html files — this script overwrites them.
The decks themselves are hand-written and are never touched.
"""
import os
import re
import sys

import teaching_data as D

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "teaching")

GENERATED = "<!-- GENERATED by build_teaching.py from teaching_data.py — do not edit by hand. -->"

# The two deck kinds an index lists, in the order they appear in a week.
KINDS = [("lecture", "Lecture"), ("live", "Live session")]

TITLE = re.compile(r"<title>(.*?)</title>", re.S | re.I)
# "LER 565 · Week 4 — Coordination Games in HR"
# "LER 565 · Week 4 Live Session — Coordination Games between HR and Management"
DECK = re.compile(r"·\s*Week\s*\d+(?:\s+Live Session)?\s*[—–-]\s*(?P<topic>.+?)\s*$", re.S)
WEEKDIR = re.compile(r"^week(\d+)$")


# ------------------------------------------------------------------ the walk
def deck_topic(path):
    """The deck's own name for itself, from its <title>.

    Falls back to the whole title if it does not follow the house format, so a
    differently-named deck still lists rather than silently vanishing.
    """
    m = TITLE.search(open(path, encoding="utf-8").read(4096))
    if not m:
        return None
    title = " ".join(m.group(1).split())
    m = DECK.search(title)
    return m.group("topic") if m else title


def weeks(course):
    """[(n, [(kind_label, href, topic), ...]), ...] for a course, in week order."""
    cdir = os.path.join(ROOT, course["dir"])
    found = []
    for name in sorted(os.listdir(cdir)):
        m = WEEKDIR.match(name)
        if not m or not os.path.isdir(os.path.join(cdir, name)):
            continue
        decks = []
        for kind, label in KINDS:
            path = os.path.join(cdir, name, kind, "index.html")
            if os.path.exists(path):
                topic = deck_topic(path)
                if topic:
                    decks.append((label, f"{name}/{kind}/", topic))
        if decks:
            found.append((int(m.group(1)), decks))
    return sorted(found)


def courses_with_decks(aff):
    return [c for c in aff["courses"] if c.get("dir")]


# --------------------------------------------------------------------- shell
CSS = """
:root{
  --accent:var(--red);
  --line:rgba(27,28,25,.15);
  --line-strong:rgba(27,28,25,.34);
  --maxw:1000px;
}
*{box-sizing:border-box;margin:0;padding:0}
html{-webkit-text-size-adjust:100%}
body{
  background:var(--paper);color:var(--ink);
  font-family:var(--sans);font-size:1.05rem;line-height:1.6;
  -webkit-font-smoothing:antialiased;overflow-x:hidden;
  min-height:100vh;display:flex;flex-direction:column;
}
a{color:inherit;text-decoration:none}
:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
.wrap{width:100%;max-width:var(--maxw);margin:0 auto;padding:0 6vw}

/* ---------- top bar ---------- */
.topbar{position:sticky;top:0;z-index:20;background:rgba(233,226,210,.86);
  backdrop-filter:blur(10px);border-bottom:1px solid var(--line)}
.topbar-in{max-width:var(--maxw);margin:0 auto;padding:.8rem 6vw;
  display:flex;align-items:center;justify-content:space-between;gap:1rem}
.brand{display:inline-flex;align-items:center;gap:.6rem;font-weight:600;font-size:1.02rem}
.brand svg{width:1.7rem;height:1.7rem;display:block;transition:transform .25s,opacity .25s}
.brand:hover svg{opacity:.82;transform:translateY(-1px)}
.tnav{display:flex;gap:1.5rem}
.tnav a{font-size:.68rem;letter-spacing:.16em;text-transform:uppercase;
  font-weight:600;color:var(--muted);transition:color .2s}
.tnav a:hover,.tnav a[aria-current]{color:var(--accent)}

/* ---------- masthead ---------- */
main{flex:1 0 auto;padding-bottom:4.5rem}
.crumb{font-size:.68rem;letter-spacing:.16em;text-transform:uppercase;
  font-weight:600;color:var(--muted);padding-top:2.6rem}
.crumb a{transition:color .2s}
.crumb a:hover{color:var(--accent)}
.crumb i{font-style:normal;opacity:.45;margin:0 .55rem}
.mast{display:flex;align-items:flex-start;justify-content:space-between;gap:2rem;padding-top:1.6rem}
.kick{display:flex;align-items:center;gap:.7rem;font-size:.7rem;letter-spacing:.2em;
  text-transform:uppercase;font-weight:600;color:var(--muted)}
.kick i{width:9px;height:9px;background:var(--red);flex:none}
h1{font-family:var(--display);font-weight:900;letter-spacing:-.02em;line-height:.95;
  font-size:clamp(2.5rem,6.5vw,4rem);margin-top:.9rem}
h1 .r{color:var(--red)}
h1.sm{font-size:clamp(2.1rem,4.6vw,2.9rem);max-width:18ch}
.sub{color:var(--muted);max-width:58ch;margin-top:1rem}
.mast-ic{flex:none;width:4.2rem;height:4.2rem;margin-top:.4rem}
.mast-ic svg{width:100%;height:100%;display:block}
.mrule{border:0;border-top:2px solid var(--ink);margin:2.4rem 0 0}

/* ---------- affiliations and courses ---------- */
.aff{padding:2.4rem 0 1.6rem;border-bottom:1px solid var(--line)}
.aff:last-of-type{border-bottom:0}
.aff-head{display:flex;align-items:baseline;justify-content:space-between;gap:1rem;flex-wrap:wrap}
.aff h2{font-family:var(--display);font-weight:900;font-size:1.75rem;letter-spacing:-.01em}
.aff .unit{color:var(--muted);font-size:.94rem}
.aff-list{margin-top:1.4rem}
.aff.bare{padding-top:.6rem}
.aff.bare .aff-list{margin-top:0}
.crs{display:grid;grid-template-columns:8.5rem 1fr auto;gap:1.4rem;align-items:baseline;
  padding:1.15rem 0;border-top:1px solid var(--line)}
.crs .code{font-size:.7rem;letter-spacing:.16em;text-transform:uppercase;
  font-weight:600;color:var(--accent)}
.crs h3{font-family:var(--sans);font-weight:500;font-size:1.22rem;letter-spacing:-.01em;
  transition:color .2s}
.crs .meta{font-size:.68rem;letter-spacing:.14em;text-transform:uppercase;
  font-weight:600;color:var(--muted);margin-top:.35rem}
.crs p{color:var(--muted);font-size:.99rem;max-width:62ch;margin-top:.45rem}
.crs .go{font-size:1.25rem;color:var(--accent);opacity:.35;transition:opacity .2s}
a.crs:hover h3{color:var(--accent)}
a.crs:hover .go{opacity:1}

/* ---------- weeks ---------- */
.weeks{margin-top:.6rem}
.wk{display:grid;grid-template-columns:5rem 1fr;gap:1.6rem;
  padding:1.35rem 0;border-top:1px solid var(--line)}
.wklab{font-size:.66rem;letter-spacing:.16em;text-transform:uppercase;
  font-weight:600;color:var(--muted)}
.wknum{font-family:var(--display);font-weight:900;font-size:2.9rem;line-height:.9;
  color:var(--ink);opacity:.2}
a.deck{display:grid;grid-template-columns:7.5rem 1fr auto;gap:1.1rem;align-items:baseline;
  padding:.55rem 0;border-bottom:1px dotted var(--rule)}
a.deck:last-child{border-bottom:0}
.deck .k{font-size:.66rem;letter-spacing:.16em;text-transform:uppercase;
  font-weight:600;color:var(--muted);transition:color .2s}
.deck .t{font-size:1.08rem;line-height:1.4;transition:color .2s}
.deck .go{color:var(--accent);opacity:0;transition:opacity .2s}
.deck:hover .t,.deck:hover .k{color:var(--accent)}
.deck:hover .go{opacity:1}
.note{color:var(--muted);font-size:.93rem;margin-top:2rem;padding-top:1.2rem;
  border-top:1px solid var(--line);max-width:62ch}

/* ---------- footer ---------- */
footer{border-top:1px solid var(--line);padding:1.5rem 0;margin-top:auto}
.foot-in{max-width:var(--maxw);margin:0 auto;padding:0 6vw;display:flex;
  justify-content:space-between;gap:1rem;flex-wrap:wrap;
  font-size:.68rem;letter-spacing:.16em;text-transform:uppercase;color:var(--muted)}

@media (max-width:700px){
  .tnav{gap:1.1rem}
  .tnav a{font-size:.64rem}
  .mast-ic{display:none}
  .crs{grid-template-columns:1fr;gap:.35rem}
  .crs .go{display:none}
  .wk{grid-template-columns:1fr;gap:.5rem}
  .wk>div:first-child{display:flex;align-items:baseline;gap:.5rem}
  .wknum{font-size:1.8rem;opacity:.28}
  a.deck{grid-template-columns:1fr;gap:.15rem;padding:.7rem 0}
  .deck .go{display:none}
}
/* The bar is a flex row that will not shrink below its contents, and on the
   narrowest phones the three links plus the name no longer fit. Publications
   goes first — it is one tap away through the name mark. */
@media (max-width:400px){
  .tnav a[href="/#selected"]{display:none}
}
"""

MARK = (
    '<svg viewBox="0 0 64 64" aria-hidden="true">'
    '<rect width="64" height="64" rx="13" fill="var(--ink)"></rect>'
    '<text x="32" y="40" text-anchor="middle" font-family="League Spartan, system-ui, sans-serif"'
    ' font-weight="900" font-size="30" letter-spacing="-1" fill="var(--paper)">RL</text>'
    '<rect x="22" y="46" width="20" height="4" rx="2" fill="var(--red)"></rect></svg>'
)

# The mortarboard from the homepage's Isotype set — same mark that labels the
# Teaching section there, so arriving here feels like the same building.
CAP = (
    '<svg viewBox="0 0 64 64" aria-hidden="true">'
    '<polygon points="32,16 58,26 32,36 6,26" fill="var(--ink)"></polygon>'
    '<path d="M21,33 L21,41 Q32,48 43,41 L43,33 Z" fill="var(--ink)"></path>'
    '<path d="M32,27 L51,34 L51,44" fill="none" stroke="var(--red)" stroke-width="2.6"'
    ' stroke-linecap="round" stroke-linejoin="round"></path>'
    '<rect x="49" y="43" width="4" height="7" rx="1.5" fill="var(--red)"></rect></svg>'
)


def crumbs(trail):
    """trail is [(label, href or None), ...]; the last item is the current page.

    The hub is its own only crumb, so it gets none — the h1 already says it.
    """
    if len(trail) < 2:
        return ""
    out = []
    for label, href in trail:
        out.append(f'<a href="{href}">{label}</a>' if href else f"<span>{label}</span>")
    return '<i>&rsaquo;</i>'.join(out)


def page(title, desc, trail, kick, h1, sub, body, h1_class=""):
    return f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow">
{GENERATED}
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="icon" href="/favicon.ico" sizes="32x32">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="stylesheet" href="/brand.css">
<style>{CSS}</style>
</head><body>

<nav class="topbar">
  <div class="topbar-in">
    <a class="brand" href="/" aria-label="Ryan Lamare — home">{MARK}<span>Ryan Lamare</span></a>
    <div class="tnav">
      <a href="/teaching/"{' aria-current="page"' if len(trail) == 1 else ''}>Teaching</a>
      <a href="/#selected">Publications</a>
      <a href="/cv/">CV</a>
    </div>
  </div>
</nav>

<main>
  <div class="wrap">
    <div class="crumb">{crumbs(trail)}</div>
    <header class="mast">
      <div>
        <div class="kick"><i></i>{kick}</div>
        <h1{h1_class}>{h1}</h1>
        {f'<p class="sub">{sub}</p>' if sub else ''}
      </div>
      <div class="mast-ic">{CAP}</div>
    </header>
    <hr class="mrule">

{body}
  </div>
</main>

<footer>
  <div class="foot-in">
    <span>&copy; <span id="yr">2026</span> J. Ryan Lamare</span>
    <span>Updated {D.UPDATED}</span>
  </div>
</footer>
<script>document.getElementById('yr').textContent = new Date().getFullYear();</script>
</body></html>
"""


# ---------------------------------------------------------------- components
def course_row(aff, c):
    """One course: a link into its decks, or out to a course guide if it has none."""
    bits = [x for x in (c.get("level"), c.get("term")) if x]
    if not c.get("dir") and c.get("external"):
        bits.append(c.get("external_label", "Course guide"))
    meta = " &middot; ".join(bits)

    inner = (
        f'        <div class="code">{c["code"]}</div>\n'
        f'        <div>\n'
        f'          <h3>{c["title"]}</h3>\n'
        + (f'          <div class="meta">{meta}</div>\n' if meta else "")
        + f'          <p>{c["blurb"]}</p>\n'
        f'        </div>\n'
        f'        <div class="go" aria-hidden="true">&rsaquo;</div>\n'
    )
    if c.get("dir"):
        open_tag = f'<a class="crs" href="/teaching/{c["dir"]}/">'
    elif c.get("external"):
        open_tag = f'<a class="crs" href="{c["external"]}" target="_blank" rel="noopener">'
    else:
        return f'        <div class="crs">\n{inner}        </div>'
    return f"        {open_tag}\n{inner}        </a>"


def aff_block(aff, heading=True):
    """An institution and its courses.

    On the affiliation's own page the masthead has already named it, so the
    heading is dropped rather than printed twice.
    """
    rows = "\n".join(course_row(aff, c) for c in aff["courses"])
    head = (
        f'      <div class="aff-head">\n'
        f'        <h2><a href="/teaching/{aff["slug"]}/">{aff["name"]}</a></h2>\n'
        f'        <div class="unit">{aff["unit"]}</div>\n'
        f'      </div>\n'
        if heading
        else ""
    )
    return (
        f'    <section class="aff{"" if heading else " bare"}">\n{head}'
        f'      <div class="aff-list">\n{rows}\n      </div>\n'
        f'    </section>'
    )


def week_block(n, decks):
    rows = "\n".join(
        f'        <a class="deck" href="{href}">'
        f'<span class="k">{label}</span>'
        f'<span class="t">{topic}</span>'
        f'<span class="go" aria-hidden="true">&rsaquo;</span></a>'
        for label, href, topic in decks
    )
    return (
        f'      <div class="wk">\n'
        f'        <div><div class="wklab">Week</div><div class="wknum">{n}</div></div>\n'
        f'        <div>\n{rows}\n        </div>\n'
        f'      </div>'
    )


# ------------------------------------------------------------------ the pages
def build_hub():
    return page(
        title="Teaching — J. Ryan Lamare",
        desc="Lecture slides and live sessions from J. Ryan Lamare's courses.",
        trail=[("Teaching", None)],
        kick="Course materials",
        h1="Teaching",
        sub=(
            "Lecture slides and live sessions, as they were taught. "
            "Everything here runs in a browser &mdash; nothing to download."
        ),
        body="\n\n".join(aff_block(a) for a in D.AFFILIATIONS),
    )


def build_affiliation(aff):
    return page(
        title=f'{aff["short"]} teaching — J. Ryan Lamare',
        desc=f'Courses taught by J. Ryan Lamare at {aff["name"]}.',
        trail=[("Teaching", "/teaching/"), (aff["short"], None)],
        kick=aff["unit"],
        h1=aff["name"],
        h1_class=' class="sm"',
        sub=None,
        body=aff_block(aff, heading=False),
    )


def build_course(aff, c):
    ws = weeks(c)
    blocks = "\n".join(week_block(n, decks) for n, decks in ws)
    note = (
        '      <p class="note">Slides open in the browser and advance with the arrow keys, '
        "space, or a tap. Every deck carries a full text version for screen readers.</p>"
    )
    body = f'    <section class="weeks">\n{blocks}\n{note}\n    </section>'
    return page(
        title=f'{c["code"]} — {c["title"]} — J. Ryan Lamare',
        desc=f'{c["code"]}, {c["title"]}: lecture slides and live sessions.',
        trail=[("Teaching", "/teaching/"), (aff["short"], f'/teaching/{aff["slug"]}/'),
               (c["code"], None)],
        kick=f'{aff["short"]} &middot; {c["code"]}',
        h1=c["title"],
        sub=c["blurb"],
        body=body,
    )


# ----------------------------------------------------------------------- main
def main():
    check = "--check" in sys.argv

    targets = [(os.path.join(ROOT, "index.html"), build_hub())]
    for aff in D.AFFILIATIONS:
        targets.append(
            (os.path.join(ROOT, aff["slug"], "index.html"), build_affiliation(aff))
        )
        for c in courses_with_decks(aff):
            targets.append(
                (os.path.join(ROOT, c["dir"], "index.html"), build_course(aff, c))
            )

    changed = []
    for path, new in targets:
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != new:
            changed.append(os.path.relpath(path, HERE))
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                open(path, "w", encoding="utf-8").write(new)

    decks = sum(
        len(d) for a in D.AFFILIATIONS for c in courses_with_decks(a) for _, d in weeks(c)
    )
    print(f"{decks} decks across {len(targets)} index pages")
    if check:
        print("CHANGED:" if changed else "up to date:", changed or "no differences")
        sys.exit(1 if changed else 0)
    print("wrote:", ", ".join(changed) if changed else "nothing (already up to date)")


if __name__ == "__main__":
    main()
