// Pavilion — the archive, headless (build step 5).
//
//   node pavilion/test/archive.test.js
//
// Three layers, in order of how much they can break:
//
//   1. `result.js` — replay a finished game and derive the winner. This is the
//      file that makes an archived result unforgeable, so it is tested against
//      real move lists and against claims that contradict them.
//   2. `archive.js` — term, roster, classification and storage, over the same
//      MemoryStore the dev relay uses.
//   3. The whole thing over real WebSockets: set a term and a roster through
//      the admin API, play a complete game between two rostered clients, and
//      check that the record wrote itself with nobody reporting anything.
//
// No dependencies and no browser, like every other suite here.

import { start, server, archive as devArchive } from '../relay/dev-relay.js';
import { Archive, MemoryStore, apiRoute, gameId } from '../relay/archive.js';
import { deriveResult, buildRecord, rankSeats, leaguePointsFor, summarize } from '../relay/result.js';
import { Relay } from '../net.js';
import { newGame, legalMoves, apply, replay } from '../engine.js';

// ---------------------------------------------------------------------------
// Harness — the same one the other suites use.

let passed = 0;
let failed = 0;

function ok(cond, msg) {
  if (cond) passed++;
  else {
    failed++;
    console.error('  FAIL: ' + msg);
  }
}

function eq(got, want, msg) {
  ok(got === want, `${msg} (got ${JSON.stringify(got)}, want ${JSON.stringify(want)})`);
}

function same(got, want, msg) {
  eq(JSON.stringify(got), JSON.stringify(want), msg);
}

function section(title) {
  console.log('— ' + title);
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function waitFor(relay, type, predicate = () => true, ms = 6000) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(`timed out waiting for "${type}"`)), ms);
    const CB = (payload) => {
      if (!predicate(payload)) return;
      clearTimeout(timer);
      relay.listeners.get(type).delete(CB);
      resolve(payload);
    };
    relay.on(type, CB);
  });
}

// A complete game, played deterministically, in the shape a finished room has.
// Nothing here is a fixture file: the moves are generated by the engine, so a
// rules change that breaks the archive breaks this suite too.
function playedRoom({ seed = 'archive-test', players = 2, seats = null, stopAfter = null } = {}) {
  let s = newGame(seed, players);
  const moves = [];
  let guard = 0;
  while (!s.over && guard++ < 600) {
    const options = legalMoves(s);
    const move = options[(moves.length * 7 + s.seatToMove) % options.length];
    moves.push({ seat: s.seatToMove, move: { ...move, t: moves.length * 1000 }, at: 1_700_000_000_000 + moves.length });
    s = apply(s, moves[moves.length - 1].move);
    if (stopAfter && moves.length >= stopAfter) break;
  }
  return {
    code: 'FERRIS-NORWAY',
    seed,
    players,
    clockMs: 300000,
    mode: 'league',
    splashHistory: true,
    startedAt: 1_700_000_000_000,
    seats:
      seats ||
      Array.from({ length: players }, (_, i) => ({
        seat: i,
        name: ['Sam', 'Alex', 'Jordan', 'Riley'][i],
        pid: ['sam', 'alex', 'jordan', 'riley'][i],
        device: i ? 'phone' : 'laptop',
        connected: true,
        id: `tok-${i}`,
      })),
    moves,
    ended: null,
    final: s,
  };
}

// ---------------------------------------------------------------------------
section('Deriving a result by replay (result.js)');

{
  const room = playedRoom();
  room.ended = { ending: 'natural' };
  const r = deriveResult(room);

  eq(r.ending, 'natural', 'a natural end stays natural');
  same(r.scores, room.final.result.scores, 'the replay reaches the same scores as playing it did');
  eq(r.winner, room.final.result.winner, 'and names the same winner');
  eq(r.plies, room.moves.length, 'the record knows how long the game was');
  ok(/^[0-9a-f]{8}$/.test(r.hash), 'and carries the final state hash as its own fingerprint');
  eq(r.points.reduce((a, b) => a + b, 0), r.winner >= 0 ? 4 : 4, 'league points total 4 over a two-player game');

  // The whole point: what the client *said* never reaches the record.
  const lying = deriveResult({ ...room }, { ending: 'natural', result: { scores: [999, 0], winner: 0 } });
  same(lying.scores, r.scores, "a client's claimed scores are ignored — the server replays instead");
}

{
  // A claim the move list does not support is not a result. It voids, with the
  // reason kept, because a game that cannot be reproduced is a bug report.
  const room = playedRoom({ stopAfter: 12 });
  const r = deriveResult(room, { ending: 'natural' });
  eq(r.ending, 'void', 'claiming a natural end the moves never reach voids the game');
  ok(/does not reach/.test(r.reason), 'and says why');
  eq(r.points, null, 'a void game scores nothing, not even the point for playing');
}

{
  const room = playedRoom();
  room.moves[3].move = { source: { type: 'source', index: 0 }, kind: 9, dest: { type: 'floor' } };
  const r = deriveResult(room, { ending: 'natural' });
  eq(r.ending, 'void', 'a move list that no longer replays voids rather than throwing');
  ok(/replay failed/.test(r.reason), 'and says the replay failed');
}

{
  // §11: timeout loses like chess. The board is mid-game, so the scores are the
  // running ones and no §8 bonus has been applied.
  const room = playedRoom({ stopAfter: 30 });
  const r = deriveResult(room, { ending: 'timeout', flagged: 0 });
  eq(r.ending, 'timeout', 'a timeout is recorded as a timeout');
  eq(r.winner, 1, 'the seat that did not flag wins');
  eq(r.flagged, 0, 'and the record says who ran out');
  same(r.points, [1, 3], 'league points follow the ranking, not the score');
  const mid = replay(room.seed, room.players, room.moves.map((m) => m.move));
  same(r.scores, mid.boards.map((b) => b.score), 'the scores are the running board scores, no end bonuses');

  const late = deriveResult(playedRoom(), { ending: 'timeout', flagged: 0 });
  eq(late.ending, 'void', 'a timeout claimed after the game had already finished voids');
}

// ---------------------------------------------------------------------------
section('Ranking and league points (§8)');

// Fabricated inputs, because a natural draw is rare enough that waiting for one
// would leave the branch untested.
same(rankSeats([61, 58], [2, 1]), [1, 2], 'higher score ranks first');
same(leaguePointsFor([1, 2]), [3, 1], 'win 3, loss 1 — inclusive totals, not bonuses');
same(rankSeats([58, 58], [1, 1]), [1, 1], 'level on score and rows is a shared first');
same(leaguePointsFor([1, 1]), [2, 2], 'a draw is 2 each');
same(rankSeats([58, 58], [2, 1]), [1, 2], 'level on score breaks on most complete rows');
same(rankSeats([70, 61, 61], [2, 1, 1]), [1, 2, 2], 'three players, two level behind');
same(leaguePointsFor([1, 2, 2]), [3, 1, 1], 'winner 3, the other two 1 each');
same(leaguePointsFor([1, 1, 3]), [2, 2, 1], 'a two-way tie for top scores 2 each, 1 for third');
same(rankSeats([90, 10, 50], [3, 0, 1], 0), [3, 2, 1], 'a flagged seat ranks last however well it was doing');

// ---------------------------------------------------------------------------
section('Term, roster and classification (archive.js)');

{
  const a = new Archive(new MemoryStore());
  same(await a.config(), { term: null, boardSize: 5, updatedAt: null }, 'a fresh archive has no term');

  const cfg = await a.setConfig({ term: '2026 Fall', boardSize: 8 });
  eq(cfg.term, '2026-fall', 'the term is slugged so it can be a storage key');
  eq(cfg.boardSize, 8, 'the public board length is a setting, not a constant');
  eq((await a.setConfig({ boardSize: 99 })).boardSize, 5, 'an absurd board length falls back to the default');
  eq((await a.setConfig({ boardSize: 8 })).term, '2026-fall', 'a partial update leaves the term alone');

  const roster = await a.setRoster([
    'Sam Okafor',
    { name: 'Alex Reed' },
    { name: 'J. Ryan Lamare', instructor: true },
    'Sam Okafor',
    '   ',
  ]);
  eq(roster.length, 4, 'blank lines are dropped');
  eq(roster[0].id, 'sam-okafor', 'ids are slugs of the name, so a re-paste keeps them');
  eq(roster[3].id, 'sam-okafor-2', 'a repeated name gets its own id rather than colliding');
  eq(roster[2].instructor, true, 'the instructor is on the roster like anyone else');

  const again = await a.setRoster(roster);
  same(again.map((r) => r.id), roster.map((r) => r.id), 're-pasting the same roster keeps every id');
}

{
  // The roster is per term, so a cohort's class list survives the next cohort
  // arriving — "who was in the 2026 class" stays answerable in 2031.
  const a = new Archive(new MemoryStore());
  eq((await a.setRoster(['Sam'])).length, 0, 'with no term set there is nowhere to put a class list');

  await a.setConfig({ term: '2026-fall' });
  await a.setRoster(['Sam Okafor', 'Alex Reed']);
  await a.setConfig({ term: '2027-summer' });
  same(await a.roster(), [], 'a new term starts with no class list rather than the last one');
  await a.setRoster(['Priya Raman']);

  same((await a.roster('2026-fall')).map((r) => r.name), ['Sam Okafor', 'Alex Reed'], 'the old cohort is still there');
  same((await a.roster()).map((r) => r.name), ['Priya Raman'], 'and the current one is its own');
  same(await a.terms(), ['2026-fall', '2027-summer'], 'the archive knows every cohort, played or not');

  // Ids are NOT scoped to the term: across cohorts the same name is the same
  // person, which is what makes an all-time Record Book possible.
  await a.setConfig({ term: '2028-fall' });
  const back = await a.setRoster(['Sam Okafor']);
  eq(back[0].id, 'sam-okafor', 'a returning student keeps the id their history is attached to');
}

{
  // Whatever was pasted in under the single global roster of the first day is
  // still readable, so nothing set up before this change was lost.
  const a = new Archive(new MemoryStore({ roster: [{ id: 'sam', name: 'Sam', instructor: false }] }));
  await a.setConfig({ term: '2026-fall' });
  same((await a.roster()).map((r) => r.name), ['Sam'], 'a legacy global roster still reads');
  await a.setRoster(['Alex']);
  same((await a.roster()).map((r) => r.name), ['Alex'], 'and the first save per term replaces it');
}

{
  const a = new Archive(new MemoryStore());
  const room = playedRoom();

  eq((await a.classify(room)).record, false, 'no term configured means nothing records');
  await a.setConfig({ term: '2026-fall' });
  eq((await a.classify(room)).record, false, 'a term alone is not enough — the seats must be on the roster');

  await a.setRoster(['Sam', 'Alex', { name: 'Ryan', instructor: true }]);
  const league = await a.classify(room);
  eq(league.record, true, 'two rostered players record');
  eq(league.mode, 'league', 'as a league game');

  const withRyan = playedRoom({ seats: [{ seat: 0, name: 'Ryan', pid: 'ryan' }, { seat: 1, name: 'Alex', pid: 'alex' }] });
  eq((await a.classify(withRyan)).mode, 'exhibition', 'a game with the instructor in it is an exhibition');

  const cup = await a.classify({ ...room, mode: 'cup' });
  eq(cup.mode, 'cup', 'the host can ask for a cup game');

  const typed = playedRoom({ seats: [{ seat: 0, name: 'Stranger', pid: null }, { seat: 1, name: 'Alex', pid: 'alex' }] });
  eq((await a.classify(typed)).record, false, 'someone who typed their name keeps the game out of the archive');
  const madeUp = playedRoom({ seats: [{ seat: 0, name: 'Sam', pid: 'not-a-student' }, { seat: 1, name: 'Alex', pid: 'alex' }] });
  eq((await a.classify(madeUp)).record, false, 'and so does an id that is not on the roster');
}

// ---------------------------------------------------------------------------
section('Writing, reading and amending a record');

{
  const a = new Archive(new MemoryStore());
  await a.setConfig({ term: '2026-fall' });
  await a.setRoster(['Sam', 'Alex', { name: 'Ryan', instructor: true }]);

  const room = playedRoom();
  room.ended = { ending: 'natural' };
  const receipt = await a.record(room, 1_700_000_100_000);
  eq(receipt.recorded, true, 'a finished game records itself');
  eq(receipt.mode, 'league', 'as a league game');

  const rec = await a.game(receipt.id);
  eq(rec.v, 1, 'the record carries the engine version it was played under');
  eq(rec.term, '2026-fall', 'and its term, from day one — the Record Book accrues across years');
  same(rec.seats, ['sam', 'alex'], 'seats are roster ids in join order');
  same(rec.names, ['Sam', 'Alex'], 'with the names kept so a record reads on its own');
  same(rec.device, ['laptop', 'phone'], 'and the device per seat, for the clock-fairness question');
  eq(rec.moves.length, room.moves.length, 'the whole move list is stored, not just the result');
  eq(rec.seed, room.seed, 'so seed + moves replays the game exactly');
  same(replay(rec.seed, rec.players, rec.moves.map((m) => m.move)).result.scores, rec.result.scores,
    'and the stored record replays back to the stored scores');

  const sum = summarize(rec);
  eq(sum.moves, undefined, 'a summary drops the move list');
  eq(sum.plies, rec.moves.length, 'but keeps how long the game was');

  const listed = await a.games('2026-fall');
  eq(listed.length, 1, 'the term lists its games');
  eq(listed[0].moves, undefined, 'as summaries, so a league table never loads a move list');
  same(await a.terms(), ['2026-fall'], 'and the archive knows which terms exist');

  // A second game in the same room — a rematch — is a different game.
  const second = playedRoom({ seed: 'archive-test-2' });
  second.startedAt = room.startedAt + 60000;
  second.ended = { ending: 'natural' };
  const r2 = await a.record(second, 1_700_000_200_000);
  ok(r2.id !== receipt.id, 'a rematch in the same room archives as its own game');
  eq((await a.games('2026-fall')).length, 2, 'both are in the term');
  eq((await a.games('2026-fall'))[0].id, r2.id, 'newest first');

  // --- the two instructor overrides ---------------------------------------
  eq((await a.setMode(receipt.id, 'cup')).mode, 'cup', 'a game can be retagged as a cup game after the fact');
  eq((await a.setMode(receipt.id, 'nonsense')).mode, 'cup', 'and nonsense leaves it alone');

  const voided = await a.setEnding(receipt.id, 'void', 'the wifi, not the player');
  eq(voided.result.ending, 'void', 'a game can be voided when the wifi was the problem');
  eq(voided.result.points, null, 'a voided game stops scoring');
  eq(voided.result.reason, 'the wifi, not the player', 'and says why');

  const restored = await a.setEnding(receipt.id, 'natural');
  same(restored.result.scores, rec.result.scores, 'un-voiding re-derives from the move list rather than trusting old numbers');
  eq((await a.game(receipt.id)).moves.length, rec.moves.length, 'and never touches the moves');

  // The trap: a voided *timeout* restored as "natural" would replay to a game
  // the moves never finish, and void itself straight back again.
  const flagged = playedRoom({ seed: 'archive-test-3', stopAfter: 30 });
  flagged.startedAt = room.startedAt + 120000;
  const t = await a.record({ ...flagged, ended: { ending: 'timeout', flagged: 1 } }, 1_700_000_300_000);
  eq((await a.game(t.id)).result.winner, 0, 'a timeout records the seat that did not flag as the winner');
  await a.setEnding(t.id, 'void', 'the wifi');
  const back = await a.setEnding(t.id, 'natural');
  eq(back.result.ending, 'timeout', 'restoring a voided timeout puts back a timeout, not a natural end');
  eq(back.result.winner, 0, 'with the same winner it had before');

  eq(await a.setMode('no-such-game', 'cup'), null, 'amending a game that is not there returns nothing');
}

// ---------------------------------------------------------------------------
section('Deleting — a demo run, not a result');

{
  const a = new Archive(new MemoryStore());
  await a.setConfig({ term: 'demo' });
  await a.setRoster(['Sam', 'Alex']);

  const ids = [];
  for (const seed of ['d1', 'd2', 'd3']) {
    const room = playedRoom({ seed });
    room.startedAt += seed.charCodeAt(1);
    room.ended = { ending: 'natural' };
    ids.push((await a.record(room)).id);
  }
  eq((await a.games('demo')).length, 3, 'three demo games');

  eq(await a.deleteGame(ids[0]), true, 'a single game can be deleted outright');
  eq(await a.game(ids[0]), null, 'and it is gone, moves and all');
  eq((await a.games('demo')).length, 2, 'and out of the term');
  eq(await a.deleteGame(ids[0]), false, 'deleting it twice is not an error, just nothing');

  // Deleting is not voiding. A void game stays in the archive on purpose —
  // it happened, and the instructor can restore it.
  await a.setEnding(ids[1], 'void', 'the wifi');
  eq((await a.games('demo')).length, 2, 'a voided game is still in the archive');

  await a.setConfig({ term: '2026-fall' });
  await a.setRoster(['Priya']);
  const keep = playedRoom({ seed: 'real' });
  keep.ended = { ending: 'natural' };
  await a.record({ ...keep, seats: [{ seat: 0, name: 'Priya', pid: 'priya' }, { seat: 1, name: 'Priya', pid: 'priya' }] });

  eq(await a.deleteTerm('demo'), 2, 'a whole cohort goes at once');
  same(await a.games('demo'), [], 'with nothing left in it');
  same(await a.roster('demo'), [], 'and its class list gone too');
  eq((await a.games('2026-fall')).length, 1, 'while every other term is untouched');
  same(await a.terms(), ['2026-fall'], 'and the deleted term stops existing');
}

{
  const a = new Archive(new MemoryStore());
  const call = (route, opts = {}) => apiRoute(a, { route, ...opts });
  await call('/admin/config', { method: 'POST', body: { term: 'demo' } });
  await call('/admin/roster', { method: 'POST', body: { roster: ['Sam', 'Alex'] } });

  eq((await call('/admin/term', { method: 'POST', body: { term: 'demo' } })).status, 400,
    'deleting a term without naming it twice is refused');
  eq((await call('/admin/term', { method: 'POST', body: { term: 'demo', confirm: 'dem' } })).status, 400,
    'and a near miss is still refused');

  const gone = await call('/admin/term', { method: 'POST', body: { term: 'demo', confirm: 'demo' } });
  eq(gone.status, 200, 'naming it twice deletes it');
  eq((await call('/session')).body.term, null, 'and deleting the term you are standing in leaves nothing recording');
}

// ---------------------------------------------------------------------------
section('The API route table');

{
  const a = new Archive(new MemoryStore());
  const call = (route, opts = {}) => apiRoute(a, { route, ...opts });

  eq((await call('/nope')).status, 404, 'an unknown route is a 404');
  same((await call('/session')).body, { term: null, boardSize: 5, roster: [] }, 'a fresh session has nothing in it');

  await call('/admin/config', { method: 'POST', body: { term: '2026-fall' } });
  await call('/admin/roster', { method: 'POST', body: { roster: ['Sam', 'Alex'] } });
  const s = (await call('/session')).body;
  eq(s.term, '2026-fall', 'the setup screen learns the term');
  eq(s.roster.length, 2, 'and who is in the class — no login, by design');

  const room = playedRoom();
  room.ended = { ending: 'natural' };
  const rec = (await call('/record', { method: 'POST', body: room })).body;
  eq(rec.recorded, true, 'a room posted to /record archives');

  const state = (await call('/admin/state')).body;
  eq(state.games.length, 1, 'the admin screen sees the term’s games');
  eq(state.config.term, '2026-fall', 'and the config');
  eq((await call('/admin/game', { query: { id: rec.id } })).body.moves.length, room.moves.length,
    'and can pull a whole game back out for a bug report');
  eq((await call('/admin/game', { query: { id: 'nope' } })).status, 404, 'and 404s on one that is not there');
}

// ---------------------------------------------------------------------------
section('Game ids');

{
  const room = playedRoom();
  const id = gameId(room, 1);
  eq(id, gameId(room, 2), 'the id comes from the room and its start time, not from when it was written');
  ok(/^[a-z0-9-]+$/.test(id), 'and is safe as a storage key and a URL segment');
  ok(gameId({ ...room, startedAt: room.startedAt + 1 }, 1) !== id, 'a rematch gets a different one');
}

// ---------------------------------------------------------------------------
section('End to end: two rostered clients, over the wire');

await start(0, true); // ephemeral port, quiet
const PORT = server.address().port;
const WS = `ws://127.0.0.1:${PORT}`;
const HTTP = `http://127.0.0.1:${PORT}`;

const api = (path, opts = {}) =>
  fetch(HTTP + path, {
    ...opts,
    headers: { 'content-type': 'application/json', authorization: 'Bearer dev', ...(opts.headers || {}) },
  });

{
  eq((await api('/api/admin/state')).status, 200, 'the instructor secret opens the admin API');
  eq(
    (await fetch(HTTP + '/api/admin/state', { headers: { authorization: 'Bearer wrong' } })).status,
    401,
    'a wrong secret does not'
  );
  eq((await fetch(HTTP + '/api/record', { method: 'POST', body: '{}' })).status, 404,
    '/record is not reachable over HTTP — only a finished room may write a game');
  eq((await fetch(HTTP + '/api/session')).status, 200, 'but the roster is public, because the class is not a secret to itself');
  eq((await fetch(HTTP + '/api/session')).headers.get('access-control-allow-origin'), '*',
    'and answers cross-origin, since the game is served from another host');
}

await api('/api/admin/config', { method: 'POST', body: JSON.stringify({ term: '2026-fall' }) });
await api('/api/admin/roster', {
  method: 'POST',
  body: JSON.stringify({ roster: ['Sam Okafor', 'Alex Reed'] }),
});

{
  const session = await (await fetch(HTTP + '/api/session')).json();
  same(session.roster.map((r) => r.id), ['sam-okafor', 'alex-reed'], 'the setup screen would list the class');

  // Two headless clients — transport plus engine, exactly what the browser
  // does underneath — picking their names off that roster.
  const players = ['sam-okafor', 'alex-reed'].map((pid, i) => {
    const relay = new Relay(WS);
    return { relay, pid, name: session.roster[i].name, state: null, seat: null, applied: 0 };
  });

  const w0 = waitFor(players[0].relay, 'welcome');
  players[0].relay.connect({
    code: null,
    hello: { name: players[0].name, pid: players[0].pid, device: 'laptop', players: 2, clockMs: 300000 },
  });
  const code = (await w0).code;

  const w1 = waitFor(players[1].relay, 'welcome');
  players[1].relay.connect({
    code,
    hello: { name: players[1].name, pid: players[1].pid, device: 'phone' },
  });
  const welcome1 = await w1;
  eq(welcome1.room.seats[0].pid, 'sam-okafor', 'the roster id travels with the seat');

  for (const p of players) {
    p.relay.on('started', (m) => {
      p.state = newGame(m.seed, m.players);
      p.seat = p.relay.seat;
    });
    p.relay.on('move', ({ ply, seat, move }) => {
      if (!p.state || ply < p.applied) return;
      p.state = apply(p.state, move);
      p.applied = ply + 1;
    });
  }

  const started = Promise.all(players.map((p) => waitFor(p.relay, 'started')));
  players[0].relay.start();
  await started;

  // Nobody sends a position and nobody reports a result: they send moves, and
  // the server works the rest out for itself.
  const receipts = players.map((p) => waitFor(p.relay, 'recorded'));
  let guard = 0;
  while (!players[0].state.over && guard++ < 600) {
    const mover = players.find((p) => p.state.seatToMove === p.seat);
    const options = legalMoves(mover.state);
    const move = options[(mover.applied * 7 + mover.seat) % options.length];
    mover.relay.move(mover.applied, { ...move, t: mover.applied * 900 });
    await sleep(3);
  }
  ok(players[0].state.over, 'the game played out to a natural finish');
  players[0].relay.over(players[0].state.result);

  const receipt = (await Promise.all(receipts))[0];
  eq(receipt.recorded, true, 'the result recorded itself — there is no submit button');
  eq(receipt.mode, 'league', 'as a league game');
  same(receipt.result.scores, players[0].state.result.scores, 'and the server derived the same scores by replaying');

  const stored = await (await api(`/api/admin/game?id=${receipt.id}`)).json();
  same(stored.seats, ['sam-okafor', 'alex-reed'], 'the record names the roster, not typed strings');
  eq(stored.moves.length, players[0].applied, 'and holds the whole game');
  eq(stored.room, code, 'and which room it was played in');
  same(
    replay(stored.seed, stored.players, stored.moves.map((m) => m.move)).result.scores,
    stored.result.scores,
    'so anyone can replay the archive and get the same answer'
  );

  const table = await (await api('/api/admin/state')).json();
  eq(table.games.length, 1, 'and it is in the term');
  ok(devArchive instanceof Archive, 'the dev relay archives through the same module the Worker does');

  players.forEach((p) => p.relay.leave());
}

{
  // A game between people who typed their names plays normally and simply does
  // not record. The game is public and carries no course branding.
  const a = new Relay(WS);
  const b = new Relay(WS);
  const wa = waitFor(a, 'welcome');
  a.connect({ code: null, hello: { name: 'Stranger', device: 'laptop', players: 2, clockMs: 0 } });
  const code = (await wa).code;
  const wb = waitFor(b, 'welcome');
  b.connect({ code, hello: { name: 'Passer-by', device: 'laptop' } });
  await wb;
  const started = waitFor(a, 'started');
  a.start();
  const info = await started;

  let s = newGame(info.seed, info.players);
  const receipt = waitFor(a, 'recorded');
  let ply = 0;
  let guard = 0;
  while (!s.over && guard++ < 600) {
    const options = legalMoves(s);
    const move = options[(ply * 7 + s.seatToMove) % options.length];
    (s.seatToMove === 0 ? a : b).move(ply, move);
    s = apply(s, move);
    ply++;
    await sleep(3);
  }
  a.over(s.result);
  const r = await receipt;
  eq(r.recorded, false, 'an unrostered game does not reach the archive');
  ok(/roster/.test(r.why), 'and says why');
  eq((await (await api('/api/admin/state')).json()).games.length, 1, 'the term still holds one game');
  a.leave();
  b.leave();
}

// ---------------------------------------------------------------------------
await sleep(50);
server.close();
console.log(`\n${passed} passed, ${failed} failed (archive, build step 5)`);
process.exit(failed === 0 ? 0 : 1);
